[package]
name = "raytracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.8"
image = "0.24"
rand = "0.8"
sdl2 = "0.35"
anyhow = "1.0"

[profile.release]
debug = 1

